### ISSUE TITLE
Freezes after updates

### ISSUE THREAD

**Issue by Rryabkov** [sfrwmaker/xtmas_neopixel#6]
Hi, before the updates in December, the program worked fine and the effects were awesome. But when I programmed a new sketch, the LED tape began to stop at one color and freezes.
Maybe I need to turn off some effects?

**Comment by sfrwmaker** [comment]
Check carefully the program free memory size. The compiler can report some kind of warning if this value is low. Try to delete some animations declaration and the entrues in the animation array.
In my own version of this strip i have used 100 leds. And in my verssion if arduino ide i have changed the compiler optimization options to short the upload code.
Just delete some animations.

**Comment by Rryabkov** [comment]
I downloaded the code in the Arduino mega and the memory problem was solved, but In animation "symRun" freezes. And I also removed animations "cToward" and "rToward". Only the first and last LEDs are on. :)

**Comment by sfrwmaker** [comment]
Sorry, i cannot reproduce the issue. I have selected "symRun", "cToward" and "rToward" animations only. Nothing hangs. On stm32 these animations are working smoothly also.

**Comment by djmcg** [comment]
Hello ,
The effects is`t nice but I also Have problem with freezes on my Arduino Nano.
From time to time is also stop when all Leds are blanked.
Could You advice how to optimize memory .
I`m beginner in coding
![Snap72](https://user-images.githubusercontent.com/27962351/100425934-6140e980-3090-11eb-86cf-c22f94ee533b.jpg)

**Comment by sfrwmaker** [comment]
Hello!
If you configure the following options to your IDE, the compiled sketch can become smaller:
-c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC

Perhaps, -Os option is the most useful in the case. The compiler options should be changed in platform.local.txt file.

Also, you can delete some animations from the list at the end of main file:
animation*  anims[] = {
              &cWipe, &cWalk, &cCreep, &cRainbow, &cRainCycle, &cRainFull, &cWave, &lUp, &sRnd, &rFade,
              &cCollEnd, &cRun, &cSeven, &mOne, &mWave, &cOne, &cFire, &cEvenOdd, &rFill, &cCollMdl,
              &cBlend, &cSwing, &cSwingS, &cFlash, &sWave, &cWorms, &cInterf, &cToward, &rToward, &lHouse,
              &cDrops, &wSeven, &fSeven, &sCreep, &symRun, &cRipe
            };
